Update gradle-publish.yml

diff --git a/.github/workflows/gradle-publish.yml b/.github/workflows/gradle-publish.yml
--- a/.github/workflows/gradle-publish.yml
+++ b/.github/workflows/gradle-publish.yml
@@ -23,7 +23,7 @@ jobs:
       uses: webfactory/ssh-agent@v0.5.4
       with:
         ssh-private-key: ${{ secrets.PRIVATE_KEY }}
-        
+
     - name: Copy files to EC2
       run: |
         scp -r -o StrictHostKeyChecking=no ./* ubuntu@${{ secrets.HOST }}:/home/ubuntu/OmaStay
@@ -65,6 +65,10 @@ jobs:
     - name: Install Docker using convenience script on EC2
       run: |
         ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=5 ubuntu@${{ secrets.HOST }} "curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh"
+
+    - name: Verify Docker installation
+      run: |
+        ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=5 ubuntu@${{ secrets.HOST }} "docker --version && sudo systemctl status docker"
 
     - name: Add ubuntu user to Docker group and restart Docker on EC2
       run: |
@@ -111,6 +115,13 @@ jobs:
           ls -la /home/ubuntu/OmaStay/nginx/certbot
           # Initial SSL certificate request
           docker-compose run --rm certbot certonly --webroot --webroot-path=/var/www/certbot -d omastay.duckdns.org -d www.omastay.duckdns.org
+          # Verify Certbot certificate issuance
+          if [ -f /etc/letsencrypt/live/omastay.duckdns.org/fullchain.pem ]; then
+              echo 'Certificate issued successfully'
+          else
+              echo 'Certificate issuance failed'
+              exit 1
+          fi
           # Restart services to apply the certificate
           docker-compose restart nginx
           # Check Certbot log for details
